services:
  minecraft-server:
    build:
      context: .
      args:
        - MINECRAFT_VERSION=${MINECRAFT_VERSION}
    image: mcserver-vanilla:${MINECRAFT_VERSION}
    container_name: minecraft-papermc-server
    stop_grace_period: 1m
    ports:
      # Player connection port
      - 0.0.0.0:25565:25565
      # RCON Access port
      - 0.0.0.0:25575:25575
      # Port for Simple Voice Chat
      - 0.0.0.0:24454:24454/udp
    restart: unless-stopped
    volumes:
      - mcworld_data:/server/world
      - mcworld_nether:/server/world_nether
      - mcworld_end:/server/world_the_end
      # Separate volume for Backuper plugin
      - mcworld_backup:/server/backup
      - ./server.properties:/server/server.properties:rw
      # Remove the following bind-mount if you aren't using the whitelist
      - ./whitelist.json:/server/whitelist.json
      # Bind-mount for plugins
      - type: bind
        source: ./plugins
        target: /server/plugins
        bind:
          create_host_path: true
      # Bind-mount for configs
      - type: bind
        source: ./config
        target: /server/config
        bind:
          create_host_path: true
volumes:
  mcworld_data:
  mcworld_nether:
  mcworld_end:
  mcworld_backup:
