services:
  minecraft-server:
    build:
      context: .
      args:
        - MINECRAFT_VERSION=${MINECRAFT_VERSION}
    image: mcserver-vanilla:${MINECRAFT_VERSION}
    container_name: minecraft-server-vanilla
    stop_grace_period: 1m
    ports:
      # Player connection port
      - 0.0.0.0:25565:25565
      # RCON Access port
      - 0.0.0.0:25575:25575
      # Port for Simple Voice Chat
      - 0.0.0.0:24454:24454/udp
    restart: unless-stopped
    volumes:
      - mcworld_data:/server/world
      - mcworld_nether:/server/world_nether
      - mcworld_end:/server/world_the_end
      # Separate volume for Backuper plugin
      - mcworld_backup:/server/backup
      - ./server.properties:/server/server.properties:rw
      # Remove the following bind-mount if you aren't using the whitelist
      - ./whitelist.json:/server/whitelist.json
      # Store plugins and server config in this directory
      - ./plugins:/server/plugins
      - ./config:/server/config
volumes:
  mcworld_data:
  mcworld_nether:
  mcworld_end:
  mcworld_backup:
